# Generated by Django 5.1.1 on 2024-10-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0028_alter_requisicoes_antenista'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
