# Generated by Django 5.1.2 on 2024-10-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t42', '0002_alter_t42model_estoque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='t42model',
            name='fazenda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
