# Generated by Django 5.1.2 on 2024-10-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0028_paradasegura_nome_do_pa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradasegura',
            name='foto_carreta',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_carreta/'),
        ),
        migrations.AddField(
            model_name='paradasegura',
            name='foto_cavalo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_cavalo/'),
        ),
    ]
