# Generated by Django 5.1.2 on 2024-10-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0030_paradasegura_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradasegura',
            name='saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paradasegura',
            name='status',
            field=models.CharField(blank=True, default='AGUARDANDO', max_length=50, null=True),
        ),
    ]
