# Generated by Django 5.1.2 on 2024-10-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0032_paradasegura_foto_carreta_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradasegura',
            old_name='foto_documento_motorista',
            new_name='cnh',
        ),
    ]
