# Generated by Django 5.1.2 on 2024-10-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0033_rename_foto_documento_motorista_paradasegura_cnh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradasegura',
            old_name='tipo_posto',
            new_name='nome_posto',
        ),
    ]
