# Generated by Django 5.1.2 on 2024-10-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0034_rename_tipo_posto_paradasegura_nome_posto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradasegura',
            old_name='nome_posto',
            new_name='tipo_posto',
        ),
    ]
